# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Danger Swift

on: [pull_request]

jobs:
  danger-swift:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch the entire history for Danger

    - name: Setup Swift
      uses: actions/setup-swift@v1
      with:
        swift-version: '5.3' # Specify your Swift version

    - name: Install Dependencies
      run: swift package resolve

    - name: Run Danger Swift
      run: swift run danger-swift ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
