# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify a Node.js version

      - name: Install Danger JS
        run: npm install -g danger

      - name: Build and Test
        run: |
          xcodebuild test -scheme DangerTest2024 -destination  -derivedDataPath Build/ -enableCodeCoverage YES
      - name: Run Danger
        run: swift run danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
